name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
        working-directory: .

      # Remove the lint and type-check step
      # - name: Lint and type-check
      #   run: npm run lint && npm run type-check
      #   working-directory: .

      - name: Build frontend
        run: npm run build
        working-directory: .

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: backEndApi

      - name: Run backend server
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
        working-directory: backEndApi

      - name: Deploy frontend
        run: |
          npm install -g serve
          nohup serve -s dist &
        working-directory: .

      - name: Keep action alive
        run: sleep infinity
